// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using laplacedemon.Data;

#nullable disable

namespace laplacedemon.Migrations
{
    [DbContext(typeof(LaPlaceDemonDataContext))]
    partial class LaPlaceDemonDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("laplacedemon.Models.CoinEnvironment.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("DateTimeOffset")
                        .HasColumnName("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("NVARCHAR(800)")
                        .HasColumnName("Name");

                    b.Property<double>("Price")
                        .HasColumnType("Float")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.ToTable("CoinObj", (string)null);
                });

            modelBuilder.Entity("laplacedemon.Models.PostEnvironment.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Bears")
                        .HasColumnType("int")
                        .HasColumnName("Bears");

                    b.Property<int>("Bulls")
                        .HasColumnType("int")
                        .HasColumnName("Bulls");

                    b.Property<int?>("CoinId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR(2000)")
                        .HasColumnName("Comment");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("DateTimeOffset")
                        .HasColumnName("Date");

                    b.Property<double>("SuggestedPrice")
                        .HasColumnType("FLOAT")
                        .HasColumnName("SuggestedPrice");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)")
                        .HasColumnName("Title");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("Bit")
                        .HasColumnName("isActive");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.HasIndex("UserId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("laplacedemon.Models.PostEnvironment.PostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("DateTimeOffset")
                        .HasColumnName("Date");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR(2000)")
                        .HasColumnName("Text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)")
                        .HasColumnName("Title");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostComment", (string)null);
                });

            modelBuilder.Entity("laplacedemon.Models.UserEnvironment.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)")
                        .HasColumnName("NickName");

                    b.Property<int?>("UserInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("UserProfileViewId")
                        .HasColumnType("int");

                    b.Property<bool>("isBloqued")
                        .HasColumnType("bit")
                        .HasColumnName("IsBloqued");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("UserProfileViewId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("laplacedemon.Models.UserEnvironment.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Photo");

                    b.Property<int>("TrustedAsAnalist")
                        .HasColumnType("int")
                        .HasColumnName("TrustedAsAnalist");

                    b.Property<string>("TrustedAsExpertAnalist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)")
                        .HasColumnName("TrustedAsExpertAnalist");

                    b.HasKey("Id");

                    b.ToTable("UserInfo", (string)null);
                });

            modelBuilder.Entity("laplacedemon.Models.UserEnvironment.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("VARCHAR(2000)")
                        .HasColumnName("Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("UserProfile", (string)null);
                });

            modelBuilder.Entity("laplacedemon.Models.UserEnvironment.UserProfileView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserVisitorId")
                        .HasColumnType("int")
                        .HasColumnName("UserVisitorId");

                    b.Property<DateTimeOffset>("ViewDate")
                        .HasColumnType("DateTimeOffset")
                        .HasColumnName("ViewDate");

                    b.HasKey("Id");

                    b.ToTable("UserProfileView", (string)null);
                });

            modelBuilder.Entity("laplacedemon.Models.PostEnvironment.Post", b =>
                {
                    b.HasOne("laplacedemon.Models.CoinEnvironment.Coin", "Coin")
                        .WithMany("Post")
                        .HasForeignKey("CoinId")
                        .HasConstraintName("FK_Post_Coin");

                    b.HasOne("laplacedemon.Models.UserEnvironment.User", "User")
                        .WithMany("Post")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Post_User");

                    b.Navigation("Coin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("laplacedemon.Models.PostEnvironment.PostComment", b =>
                {
                    b.HasOne("laplacedemon.Models.PostEnvironment.Post", "Post")
                        .WithMany("PostComments")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_PostComment_Post");

                    b.HasOne("laplacedemon.Models.UserEnvironment.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("laplacedemon.Models.UserEnvironment.User", b =>
                {
                    b.HasOne("laplacedemon.Models.UserEnvironment.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserInfoId");

                    b.HasOne("laplacedemon.Models.UserEnvironment.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId");

                    b.HasOne("laplacedemon.Models.UserEnvironment.UserProfileView", "UserProfileView")
                        .WithMany()
                        .HasForeignKey("UserProfileViewId");

                    b.Navigation("UserInfo");

                    b.Navigation("UserProfile");

                    b.Navigation("UserProfileView");
                });

            modelBuilder.Entity("laplacedemon.Models.CoinEnvironment.Coin", b =>
                {
                    b.Navigation("Post");
                });

            modelBuilder.Entity("laplacedemon.Models.PostEnvironment.Post", b =>
                {
                    b.Navigation("PostComments");
                });

            modelBuilder.Entity("laplacedemon.Models.UserEnvironment.User", b =>
                {
                    b.Navigation("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
